# Generated by Django 4.2.5 on 2024-01-04 19:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='my_name', max_length=255)),
                ('regid', models.CharField(default=uuid.UUID('47d3f264-4fa6-4e05-a74b-b7adcd071d6a'), max_length=255)),
                ('gdate', models.CharField(default='Thu Jan  4 20:50:52 2024', max_length=255)),
                ('category', models.CharField(default='category', max_length=255)),
                ('contact', models.CharField(default='contact', max_length=255)),
                ('dofbirth', models.CharField(default='December 30 2004', max_length=255)),
                ('size', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Registers',
            },
        ),
    ]
