# Generated by Django 4.2.5 on 2024-01-04 19:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='gdate',
            field=models.CharField(default='Thu Jan  4 20:53:46 2024', max_length=255),
        ),
        migrations.AlterField(
            model_name='register',
            name='regid',
            field=models.CharField(default=uuid.UUID('47c999a0-2b94-4087-8cfb-37f5ef2029d6'), max_length=255),
        ),
    ]
