# Generated by Django 4.2.5 on 2024-01-08 11:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_register_gdate_alter_register_regid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='gdate',
            field=models.CharField(default='Mon Jan  8 12:07:12 2024', max_length=255),
        ),
        migrations.AlterField(
            model_name='register',
            name='regid',
            field=models.CharField(default=uuid.UUID('654b6f62-a9df-464b-927d-7abb06084f6d'), max_length=255),
        ),
    ]
