# Generated by Django 4.2.1 on 2024-04-29 11:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0004_alter_register_gdate_alter_register_regid'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentInitialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('time', models.CharField(default=datetime.datetime(2024, 4, 29, 12, 57, 40, 521053))),
                ('transactionId', models.CharField(default=uuid.UUID('a8fa5f1a-27cc-418f-9520-8b6e61ed668f'))),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Register',
        ),
    ]
