# Generated by Django 4.2.1 on 2024-12-17 15:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_profile_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userid',
            field=models.CharField(default=uuid.UUID('df98f0c3-7246-4e07-82db-3774e3afa023')),
        ),
    ]
