# Generated by Django 4.2.1 on 2024-12-17 15:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_profile_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userid',
            field=models.CharField(default=uuid.UUID('ba1cefaf-b8a6-4e90-b774-90b3c7e6d5da')),
        ),
    ]
