# Generated by Django 4.2.1 on 2024-04-29 13:35

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_profile_userid_alter_paymentinitialization_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinitialization',
            name='status',
            field=models.CharField(default='success'),
        ),
        migrations.AlterField(
            model_name='paymentinitialization',
            name='time',
            field=models.CharField(default=datetime.datetime(2024, 4, 29, 14, 35, 5, 981046)),
        ),
        migrations.AlterField(
            model_name='paymentinitialization',
            name='transactionId',
            field=models.CharField(default=uuid.UUID('0f0ea106-2d5e-4f40-ab6a-ca43d3bce415')),
        ),
        migrations.AlterField(
            model_name='profile',
            name='userid',
            field=models.CharField(default=uuid.UUID('2d61266f-bfb0-46a6-b35e-8f57fad513c8')),
        ),
    ]
