# Generated by Django 4.2.1 on 2024-12-17 15:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_profile_userid_useraccount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraccount',
            options={'verbose_name': 'User Account', 'verbose_name_plural': 'User Accounts'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='userid',
            field=models.CharField(default=uuid.UUID('9e083907-98ee-40f4-9679-d5426b33d826')),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='account_number',
            field=models.CharField(default=uuid.UUID('05aeeeb5-cb68-4f28-b8a2-84073c2ee50d'), max_length=40),
        ),
    ]
