# Generated by Django 4.2.1 on 2024-12-17 15:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_useraccount_options_alter_profile_userid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userid',
            field=models.CharField(default=uuid.UUID('0d9b8202-3cbf-4821-8bf1-a9b23dc88ca1')),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='account_number',
            field=models.CharField(default=uuid.UUID('dc9c12e4-61b5-4215-a04b-d54e34d2fa70'), max_length=40),
        ),
    ]
