# Generated by Django 4.2.1 on 2024-06-17 13:21

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_paymentinitialization_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userwallet',
            name='user',
        ),
        migrations.AddField(
            model_name='payment',
            name='Payer',
            field=models.CharField(default='marty', max_length=200),
        ),
        migrations.AddField(
            model_name='userwallet',
            name='owner',
            field=models.CharField(default='marty', max_length=200),
        ),
        migrations.AlterField(
            model_name='paymentinitialization',
            name='time',
            field=models.CharField(default=datetime.datetime(2024, 6, 17, 14, 21, 50, 402421)),
        ),
        migrations.AlterField(
            model_name='paymentinitialization',
            name='transactionId',
            field=models.CharField(default=uuid.UUID('2076b04b-f600-4424-bc52-74c9d821ecd4')),
        ),
        migrations.AlterField(
            model_name='profile',
            name='userid',
            field=models.CharField(default=uuid.UUID('c289a4ee-0212-43d1-9cec-0fcd135751a2')),
        ),
    ]
