# Generated by Django 4.2.1 on 2024-06-17 13:30

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_payment_user_remove_userwallet_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinitialization',
            name='time',
            field=models.CharField(default=datetime.datetime(2024, 6, 17, 14, 30, 37, 32463)),
        ),
        migrations.AlterField(
            model_name='paymentinitialization',
            name='transactionId',
            field=models.CharField(default=uuid.UUID('3ceac522-f19d-4bb5-9082-2f71acb01735')),
        ),
        migrations.AlterField(
            model_name='profile',
            name='userid',
            field=models.CharField(default=uuid.UUID('5f88d2cc-d7bb-4186-83d6-db20e205d3d6')),
        ),
    ]
