# Generated by Django 4.2.1 on 2024-06-17 14:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_paymentinitialization_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='userid',
            field=models.CharField(default=uuid.UUID('fd6d9bed-eb4a-404c-8071-0d288032a17e')),
        ),
        migrations.DeleteModel(
            name='PaymentInitialization',
        ),
    ]
